# Generated by Django 3.2 on 2023-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
