# Generated by Django 3.2 on 2023-02-28 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230228_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Набор символов неверный', regex='^[\\w.@+-]+\\z')]),
        ),
    ]
