# Generated by Django 3.2 on 2023-02-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_rating_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг произведения'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
